apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cas-gitea.fullname" . }}-data
  labels:
{{ include "cas-gitea.labels" . | indent 4 }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
